---
- name: install pip packages
  pip:
    executable: pip3.4
    requirements: /tmp/requirements.txt

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: "restart {{appname}}"
  service:
    name: "{{appname}}"
    state: restarted
