---
- name: update the cache
  apt:
    update_cache: yes
    cache_valid_time: 14400

- name: Install mysql-server and other relevant parts
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-mysqldb
    - mysql-server-5.5

- name: Bring over the mysqloverrides file
  copy:
    src: web.cnf
    dest: /etc/mysql/conf.d/web.cnf
    owner: root
    group: root
  notify: restart mysql


- name: Set up the root user for mysql
  mysql_user:
    name: root
    password: "{{rootpassword}}"
  ignore_errors: yes


- name: Create the notesdb database
  mysql_db:
    name: notesdb
    login_user: root
    login_password: "{{rootpassword}}"
    state: present


- name: Set up the mysql regular user
  mysql_user:
    name: vagrant
    host: "192.168.33.10"
    password: "{{userpassword}}"
    priv: "notesdb.*:ALL"
    state: present
    login_user: root
    login_password: "{{rootpassword}}"
