---
- name: Run the apt package updates
  apt:
    update_cache: yes
    cache_valid_time: 14400


- name: Install core apt packages (nginx, python3-pip)
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
    - nginx
    - python3-pip
    - mysql-client-5.5

- name: Send in the requirements.txt file.
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt
  notify: install pip packages

- name: Setup folders
  file:
    dest: "{{item}}"
    owner: www-data
    group: www-data
    mode: 0770
    state: directory
  with_items:
    - "/var/app/{{appname}}"
    - "/var/log/{{appname}}"
    - "/var/www/{{appname}}"

- name: Copy over core application files.
  copy:
    src: "{{item}}"
    dest: "/var/app/{{appname}}/{{item}}"
    owner: www-data
    group: www-data
    mode: 0664
  with_items:
    - view.py
    - model.py
    - config.ini
  notify: "restart {{appname}}"


- name: Copy over html and javascript static assets
  copy:
    src: static
    dest: "/var/www/{{appname}}/"
    mode: 0664
    owner: www-data
    group: www-data

- name: copy over nginx template
  template:
    src: nginx_template.conf
    dest: "/etc/nginx/sites-available/{{appname}}.conf"
    mode: 0664
    owner: www-data
    group: www-data
  notify: restart nginx


- name: copy over the uwsgi template
  template:
    src: uwsgi_config.template
    dest: "/var/app/{{appname}}/{{appname}}.ini"
    mode: 0664
    owner: www-data
    group: www-data
  notify: "restart {{appname}}"


- name: symlink setup
  file:
    path: "/etc/nginx/sites-enabled/{{appname}}.conf"
    src: "/etc/nginx/sites-available/{{appname}}.conf"
    state: link
  notify: restart nginx


- name: Copy over the upstart service script
  template:
    src: upstart.template
    dest: "/etc/init/{{appname}}.conf"
    owner: www-data
    group: www-data
    mode: 0660
  notify: "restart {{appname}}"
